//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Name { get; set; }
        public long StudentNum { get; set; }
        public int Id { get; set; }
        public string Class { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public string Password { get; set; }
        public string pic { get; set; }
        public string Email { get; set; }
    }
}
