//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LXC_OnlineLearningEntities : DbContext
    {
        public LXC_OnlineLearningEntities()
            : base("name=LXC_OnlineLearningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<part> part { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<TeacherAccount> TeacherAccount { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Test_question> Test_question { get; set; }
    }
}
