//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int Id { get; set; }
        public string A_op { get; set; }
        public string B_op { get; set; }
        public string C_op { get; set; }
        public string D_op { get; set; }
        public string correct_op { get; set; }
        public string Image { get; set; }
        public int PartId { get; set; }
        public int score { get; set; }
        public string Question1 { get; set; }
    }
}
